// jpg_state.c generated by gen_state from jpg_state.json and jsp_state.skel.c
// manual edits to jpg_state.skel.c will be reflected in jpg_state.c
// manual edits to jpg_state.c will be discarded

#include <stdint.h>
#include "jpg.c"

uint8_t state_map[][256] = {
<= map

};

typedef enum {
<= enums
,
        state_error = 0xFF
} state;

jpg_type jpg_next(jpg_parser p) {
        while(1) {
                while(p->current < p->last) {
                        state current_state = state_map[p->state][*p->current];
                        if(!(current_state & 0x80)) {
                                p->state = current_state;
                                p->current++;
                                continue;
                        }

                        jpg_type result = JPG_NONE;
                        state new_state = state_error;
                        int incr = 1;
                        switch(current_state) {
<= code

                        }

                        if(new_state == state_error)
                                return jpg_parse_error(p);

                        parser->state = new_state;
                        p->current += incr;

                        if(result != JPG_NONE) {
                                return result;
                        }
                }
                if(p->seen_eof)
                        return (p->token_ptr == 0)
                               ? JPG_EOF
                               : jpg_parse_error(p);
                else if(-1 == parser_read_next(p))
                        return jpg_reader_error(p);
        }
}
