// state.c generated by gen_state from state.json and state.skel.c
// manual edits to state.skel.c will be reflected in state.c
// manual edits to state.c will be discarded

#include <stdint.h>
#include "state_code.c"

uint8_t state_map[][256] = {
<= map

};

typedef enum {
<= enums
,
        state_error = 0xFF
} state;

jsonpg_type jsonpg_next(jsonpg_parser p) {
        while(1) {
                while(p->current < p->last) {
                        state current_state = state_map[p->state][*p->current];
                        if(!(current_state & 0x80)) {
                                p->state = current_state;
                                p->current++;
                                continue;
                        }

                        jsonpg_type result = JSONPG_NONE;
                        state new_state = state_error;
                        int incr = 1;
                        switch(current_state) {
<= code

                        }

                        if(new_state == state_error)
                                return jsonpg_parse_error(p);

                        parser->state = new_state;
                        p->current += incr;

                        if(result != JSONPG_NONE) {
                                return result;
                        }
                }
                if(p->seen_eof)
                        return (p->token_ptr == 0)
                               ? JSONPG_EOF
                               : jsonpg_parse_error(p);
                else
                        parser_read_next(p);
        }
}
