// state.c generated by gen_state from state.json and state.skel.c
// manual edits to state.skel.c will be reflected in state.c
// manual edits to state.c will be discarded

#include <stdint.h>
#include "state_code.c"

uint8_t state_map[][256] = {
<= map

};

typedef enum {
<= enums
,
        state_error = 0xFF
} state;

jsonn_type jsonn_parse2_next(jsonn_parser p) {
        jsonn_type result = JSONN_EOB;
        while(p->current < p->last) {
                state current_state = state_map[p->state][*p->current];
                if(current_state < 0x80) {
                        p->state = current_state;
                        p->current++;
                        continue;
                }
                state new_state = state_error;
                int incr = 1;
                switch(current_state) {
<= code

                }
                if(new_state == state_error) {
                        result = parse_error(p);
                        break;
                }
                parser->state = new_state;
                parser->current += incr;
                if(result != JSONN_EOB)
                        break;
        }
        if(p->current == p->last)
                parse_stash(p);
        return result;
}
